name: Update filtered hosts

on:
  workflow_dispatch:
  schedule:
    - cron: "17 */6 * * *"  # каждые 6 часов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate hosts
        run: python filter_hosts.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add hosts
          git diff --cached --quiet && exit 0
          git commit -m "Update hosts"
          git push
